#!/usr/bin/env python3
"""
convert_gifs.py  —  PlatformIO pre-build script
================================================
Scans the project's images/ folder for *.gif files and generates a
corresponding C++ header in src/generated/ for each one.

Each GIF frame is scaled/cropped to fit the LED matrix (MATRIX_W x MATRIX_H)
and stored as a flat array of CRGB-compatible uint32_t values (0x00RRGGBB).

Generated header example  (src/generated/demo_gif.h):
------------------------------------------------------
    #pragma once
    #include <Arduino.h>

    // demo.gif  —  60×8, 12 frames, 100 ms/frame
    #define DEMO_GIF_W       60
    #define DEMO_GIF_H        8
    #define DEMO_GIF_FRAMES  12
    #define DEMO_GIF_DELAY  100   // ms

    extern const uint32_t DEMO_GIF_DATA[12][480] PROGMEM;

And a matching .cpp in src/generated/ with the actual data.
"""

import os
import sys
import math
from pathlib import Path

# ── PIL / Pillow ──────────────────────────────────────────────────────────────
try:
    from PIL import Image
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow", "-q"])
    from PIL import Image

# ── Paths ─────────────────────────────────────────────────────────────────────
Import("env")  # PlatformIO SCons environment

project_dir = env.subst("$PROJECT_DIR")
images_dir  = Path(project_dir) / "images"
output_dir  = Path(project_dir) / "src" / "generated"
output_dir.mkdir(parents=True, exist_ok=True)

# ── Matrix dimensions (must match config.h) ───────────────────────────────────
MATRIX_W = 60
MATRIX_H = 8

# ── Helpers ───────────────────────────────────────────────────────────────────

def fit_frame(frame: Image.Image, w: int, h: int) -> Image.Image:
    """Scale frame to fit w×h, centre-crop, return as RGB."""
    frame = frame.convert("RGB")
    fw, fh = frame.size
    # Scale so the frame covers the target size (cover, not contain)
    scale = max(w / fw, h / fh)
    new_w = math.ceil(fw * scale)
    new_h = math.ceil(fh * scale)
    frame = frame.resize((new_w, new_h), Image.LANCZOS)
    # Centre crop
    left = (new_w - w) // 2
    top  = (new_h - h) // 2
    return frame.crop((left, top, left + w, top + h))


def get_frame_delay(gif: Image.Image) -> int:
    """Return the delay of the first frame in ms (default 100 ms)."""
    try:
        return gif.info.get("duration", 100)
    except Exception:
        return 100


def safe_name(stem: str) -> str:
    """Convert filename stem to a valid C identifier."""
    return "".join(c if c.isalnum() else "_" for c in stem).upper()


# ── Process each GIF ─────────────────────────────────────────────────────────

# ── Clean up any stale generated files first ─────────────────────────────────
for old in output_dir.glob("*.h"):
    if old.name != ".gitkeep":
        old.unlink()
for old in output_dir.glob("*.cpp"):
    old.unlink()

gif_files = sorted(images_dir.glob("*.gif")) + sorted(images_dir.glob("*.GIF"))

if not gif_files:
    print("[convert_gifs] No GIF files found in images/  — skipping.")
else:
    for gif_path in gif_files:
        stem    = gif_path.stem
        cname   = safe_name(stem)          # e.g. DEMO_GIF
        h_name  = f"{stem.lower()}.h"
        cpp_name= f"{stem.lower()}.cpp"
        h_path  = output_dir / h_name
        cpp_path= output_dir / cpp_name

        print(f"[convert_gifs] Converting {gif_path.name}  →  {h_name} + {cpp_name}")

        gif = Image.open(gif_path)
        delay = get_frame_delay(gif)

        frames = []
        try:
            while True:
                frame = fit_frame(gif.copy(), MATRIX_W, MATRIX_H)
                pixels = list(frame.getdata())  # list of (R,G,B) tuples
                frames.append(pixels)
                gif.seek(gif.tell() + 1)
        except EOFError:
            pass

        n_frames = len(frames)
        n_pixels = MATRIX_W * MATRIX_H

        # ── Write header ──────────────────────────────────────────────────────
        with open(h_path, "w") as f:
            f.write(f"// Auto-generated by convert_gifs.py — do not edit\n")
            f.write(f"// Source: {gif_path.name}  |  {MATRIX_W}x{MATRIX_H}  |  {n_frames} frames  |  {delay} ms/frame\n")
            f.write(f"#pragma once\n")
            f.write(f"#include <Arduino.h>\n\n")
            f.write(f"#define {cname}_W       {MATRIX_W}\n")
            f.write(f"#define {cname}_H       {MATRIX_H}\n")
            f.write(f"#define {cname}_FRAMES  {n_frames}\n")
            f.write(f"#define {cname}_DELAY   {delay}  // ms per frame\n\n")
            f.write(f"// Each pixel stored as 0x00RRGGBB\n")
            f.write(f"extern const uint32_t {cname}_DATA[{n_frames}][{n_pixels}] PROGMEM;\n")

        # ── Write cpp ─────────────────────────────────────────────────────────
        with open(cpp_path, "w") as f:
            f.write(f"// Auto-generated by convert_gifs.py — do not edit\n")
            f.write(f"#include <Arduino.h>\n")
            f.write(f"#include \"{h_name}\"\n\n")
            f.write(f"const uint32_t {cname}_DATA[{n_frames}][{n_pixels}] PROGMEM = {{\n")
            for fi, frame_pixels in enumerate(frames):
                f.write(f"  // frame {fi}\n  {{\n")
                cols = []
                for r, g, b in frame_pixels:
                    cols.append(f"0x{r:02X}{g:02X}{b:02X}u")
                # 8 values per line for readability
                lines = [cols[i:i+8] for i in range(0, len(cols), 8)]
                f.write(",\n".join("    " + ", ".join(l) for l in lines))
                f.write("\n  }")
                if fi < n_frames - 1:
                    f.write(",")
                f.write("\n")
            f.write("};\n")

        print(f"[convert_gifs]   {n_frames} frames  {delay} ms/frame  →  {n_pixels * n_frames * 4} bytes in flash")

print("[convert_gifs] Done.")
